[workspace]
members = [
    "./crates/abi",
    "./crates/api",
    "./crates/db",
    "./crates/entity",
    "./crates/migration",
    "./crates/entity",
    "./crates/doc_index", "crates/storage",
]

resolver = "2"
