[package]
name = "abi"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.8", features = ["v4"] }
chrono = { version = "0.4" }
thiserror = { version = "1.0" }

tracing = { version = "0.1" }
async-trait = { version = "0.1" }
